# Site settings
author: Sasha W
title: ItsChoc's World
header-img: img/home-bg.png
email: sashawalker31@gmail.com
copyright_name: Sasha W
description: > # this means to ignore newlines until "baseurl:"
  Come journey with me through love, life, and code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sashawalker31

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
